@startuml
'https://plantuml.com/sequence-diagram

autoactivate on

actor Manager as M
participant "ApproveRejectEnrollmentUI" as UI
participant "ApproveRejectEnrollmentController" as C
participant "ListCoursesService" as CS
participant "ListStudentsService" as SS
participant "CourseEnrollmentRequestService" as ES
participant "CourseEnrollmentRequest" as E
database "CourseEnrollmentRequestRepository" as R
database "CourseRepository" as CR



M->UI: Asks to see enrollments requests
UI->C:create
UI->C:getEnrollmentCourses()
C->CS:getEnrollmentCourses()
CS->CR:getEnrollmentCourses()
CR-->CS:lisfOfEnrollStateCourses
deactivate CR
CS-->C: lisfOfEnrollStateCourses
C-->UI: lisfOfEnrollStateCourses
UI-->M: Shows a list of courses
M->UI: Chooses course
UI->C: studentsCourseEnrollment(course)
C->SS: allUsers(), findAllStudents()
SS-->C :allStudents
UI->UI:showAllUsers()
M->UI: approve, reject
UI->C:approveStudentsEnrollment(approvals,selectedCourse), rejectStudentsEnrollment(rejections,selectedCourse)
C->ES:getStudentEnrollment(user, course)
ES-->E: approveEnrollment(user)
ES-->C: requestUpdate
C->R:save(requestUpdate)

@enduml