@startuml
autonumber

autoactivate on

actor Teacher
activate Teacher

alt
Teacher -> System: Asks to create an exam
System --> Teacher: Ask for sequence section information
Teacher -> System: Insert sequence section information
System --> Teacher: Asks question information
Teacher -> System: Insert question information
System --> Teacher: Asks exam information
Teacher -> System: Insert exam information
else

Teacher -> System: Asks to update an exam
System --> Teacher: Ask for course
Teacher -> System: Select course
System --> Teacher: Shows list of exams
Teacher -> System: Select exam
System --> Teacher: Shows exam
Teacher -> System: Updates exam
end
System --> Teacher: Saves exam


deactivate Teacher

@enduml