@startuml
autonumber

autoactivate on

actor Student
activate Student


Student -> System: Asks to take a exam
System --> Student: Shows all Courses that are enrolled
Student -> System: Select course
System --> Student: shows all exams for this course that are unsolved
Student -> System: Select a exam to unsolved
alt if exam is inside periodo of submission
System --> Student: Begin exam
loop until have question to make
System --> Student: make question
Student -> System: Answer the question
end
System --> Student: Show grade and feedback
end
deactivate Student

@enduml