@startuml
'https://plantuml.com/use-case-diagram


actor Student
    Student -down-> (Authenticates to the system)
    (Authenticates to the system) --> (Select the option Exams)
    (Select the option Exams) --> (Selects the option to view His exams)
    (Selects the option to view His exams) --> (The Exams for the courses he is enrolled are shown)


@enduml
