@startuml
'https://plantuml.com/use-case-diagram

actor User
    User -down-> (Authenticates to the system)
    (Authenticates to the system) --> (Select the option to Schedule Meeting)
    (Select the option to Schedule Meeting) --> (Put all information required : name, date, hour, duration, participants)
  (Put all information required : name, date, hour, duration, participants) --> (Save)

@enduml