@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant ListMeetingsUI      as UI <<Presentation>>
control ListMettingsController  as Controller <<Application>>
participant ListMeetingsService as Service <<Application>>
participant PersistenceContext  as Persistence <<persistence>>
database MettingsRepository     as Repository <<Repository>>
participant "Mettings"          as Mettings <<Domain>>

activate User
User -> UI                  : Select the option - 8.Meeting
activate UI
UI -> Controller            : allMeetings()
activate Controller
Controller -> Service       : allMeetings()
deactivate Controller
activate Service
Service --> UI              : ListAllMeetings
deactivate Service
UI --> User                 : Shows the ListAllMeetings
User -> UI                  : Selects the Meeting




@enduml