@startuml
'https://plantuml.com/use-case-diagram




actor Manager
    Manager -down-> (Authenticates to the system)
    (Authenticates to the system) --> (Select the option to open and close Courses)
    (Select the option to open and close Courses) --> (The manager chooses if wants to open or close a Course)

  (The manager chooses if wants to open or close a Course) --> (Save)
  (The manager chooses if wants to open or close a Course) --> (Cancel)


@enduml
