@startuml
'https://plantuml.com/use-case-diagram


actor User
    User -down-> (Authenticates to the system)
    (Authenticates to the system) --> (Select the option to create a Shared Board)
    (Select the option to create a Shared Board) --> (Fill the request data and optional shares)

  (Fill the request data and optional shares) --> (Save)
  (Fill the request data and optional shares) --> (Cancel)


@enduml
