@startuml
'https://plantuml.com/class-diagram

class OpenAndCloseCoursesUI  {

}

class OpenAndCloseCoursesController {

}

class CoursesRepository {

}

class Courses {

}

OpenAndCloseCoursesUI -down-> OpenAndCloseCoursesController: uses the controller
OpenAndCloseCoursesController --> CoursesRepository: uses the repository
OpenAndCloseCoursesController --> Courses: changes status


@enduml