l@startuml
'https://plantuml.com/use-case-diagram




actor Manager
    Manager -down-> (Authenticates to the system)
    (Authenticates to the system) --> (Select the option to update the Courses)
    (Select the option to update the Courses) --> (Types the name of the Course)
    (Types the name of the Course) --> (Types the newState)

  (Types the newState) --> (Save)
  (Types the newState) --> (Cancel)


@enduml
