@startuml

class User

class PostIt{
    -Id
    -Board
    -Columns
    -Rows
    -Owner
    -ContentText
    -ContentImage
    -Post-It History
    -Access
    -Action
}



class Board{
    -Id
    -Title
    -Shares
    -Archive
    -Owner
    -Board History
    -Columns
}

class SharedBoardSynchronizationUI

class SharedBoardSynchronizationController

User-->SharedBoardSynchronizationUI
SharedBoardSynchronizationUI-->SharedBoardSynchronizationController
SharedBoardSynchronizationController-->Board
Board-->PostIt

@enduml