@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Actor
activate Actor
note right of Actor: Existe um serviço com a responsabilidade de verificar a disponibilidade do professor no dia marcado e a propagação da lesson para a frequencia estipulada
participant ScheduleRecurringLessonUI as UI <<Presentation>>
participant ScheduleRecurringLessonController as Controller <<Application>>
database ScheduleRecurringLessonRepository as LessonRepository <<Repository>>
participant "serviço:RecurringLessonScheduler" as Serviço <<Domain>>
participant RecurringLesson as RecurringLesson <<Domain>>


Actor -> UI: CreateRecurringLesson()
activate UI
UI -> Actor: Ask User the recurring lesson information
Actor -> UI: inputs frequency, start date, end date, duration,\n title and start time

UI -> Controller: ScheduleRecurringClass(frequency, startDate, endDate, duration, title, startTime)
activate Controller
Controller -> RecurringLesson: createNewRecurringLesson()
activate RecurringLesson
Controller -> Serviço: checkTeacherAvailability()
activate Serviço
Controller -> Serviço: propagateLessonByFrequency()
Controller -> LessonRepository: save()
activate LessonRepository
UI <- Controller: RecurringLesson
Actor <- UI: back to menu


@enduml