@startuml
autonumber

autoactivate on

actor User
activate User


User -> System: Asks to Cancel a meeting
System --> User: Show list of meeting of this user\n ask to select one
User -> System: Select meeting to cancel
System --> User: meeting canceled

deactivate User

@enduml