@startuml
actor User as Actor
participant ListCourseUI as UI <<presentation>>
participant ListCourseController as Controller <<aplication>>
participant ListCoursesService as Service <<service>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database CourseRepository as Repository <<repository>>

Actor -> UI: show()
activate UI
    UI -> Controller: allCourses()
        activate Controller
        Controller -> Service: allCourses()
        activate Service
        Service -> Persistence: Repositories()
        activate Persistence
        Persistence -> Factory: Courses()
                    activate Factory
            Factory -> Repository: create

            deactivate Factory
        Service -> Repository: allCourses()
                activate Repository
        Repository --> Service
        deactivate Repository
        Service--> Controller
        deactivate Service
        Controller --> UI: List
    deactivate Controller
    UI -> UI:Show
deactivate UI
@enduml