@startuml
'https://plantuml.com/use-case-diagram

actor Manager
    Manager -down-> (Authenticates to the system)
    (Authenticates to the system) --> (Select the option to List Courses)
    (Select the option to List Courses) --> (show all courses)


@enduml