@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User


User -> CreateSharedBoardUI: Select the option to create Shared Board
activate CreateSharedBoardUI
control CreateSharedBoardController

CreateSharedBoardUI -> CreateSharedBoardController: create
activate CreateSharedBoardController
CreateSharedBoardUI --> User: Requests data
User -> CreateSharedBoardUI: Insert title, numberOfColumns, numberOfRows
    loop option < 11
        CreateSharedBoardUI --> User: Requests the name of the columns
        User -> CreateSharedBoardUI: Types names of the columns
    end
     loop option < 21
            CreateSharedBoardUI --> User: Requests the name of the rows
            User -> CreateSharedBoardUI: Types names of the rows
        end


CreateSharedBoardUI -> CreateSharedBoardController: addSharedBoard(title, numberOfColumns,\n numberOfRows, columnsList, rowsList)

CreateSharedBoardController -> CreateSharedBoardBuilder: create
CreateSharedBoardController -> CreateSharedBoardBuilder: withTitle(title)
note left of CreateSharedBoardBuilder: set the rest of the parameters
CreateSharedBoardController -> CreateSharedBoardBuilder: build()
CreateSharedBoardBuilder -> SharedBoard: create(title, owner..........................)
activate SharedBoard
activate CreateSharedBoardBuilder
SharedBoard --> CreateSharedBoardBuilder: SharedBoard


CreateSharedBoardBuilder --> CreateSharedBoardController: SharedBoard
deactivate CreateSharedBoardBuilder
CreateSharedBoardController -> PersistenceContext: repositories()
activate PersistenceContext

note right of PersistenceContext: pode criar repositório em memória ou JPA
PersistenceContext -> RepositoryFactory: create()
database SharedBoardRepository
PersistenceContext --> CreateSharedBoardController : factory
deactivate PersistenceContext
CreateSharedBoardController -> RepositoryFactory: SharedBoard()
activate RepositoryFactory
RepositoryFactory -> SharedBoardRepository : create
RepositoryFactory --> CreateSharedBoardController: SharedBoardRepository
deactivate RepositoryFactory
CreateSharedBoardController -> SharedBoardRepository: save(SharedBoard)
CreateSharedBoardController --> CreateSharedBoardUI: SharedBoard
deactivate CreateSharedBoardController

CreateSharedBoardUI --> User: Displays SharedBoard Info

deactivate CreateSharedBoardController


@enduml