@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Manager

Manager -> UpdateCourseStateUI: Select the option 3. Update Course State
UpdateCourseStateUI -> UpdateCourseStateController: allCourses()
UpdateCourseStateController --> ListCourseService: allCourses()
ListCourseService --> UpdateCourseStateUI: ListAllCourses
UpdateCourseStateUI --> Manager:  Shows the List of Courses
Manager -> UpdateCourseStateUI: Selects the course
UpdateCourseStateUI --> Manager: Request the newState
Manager -> UpdateCourseStateUI: Types the newState
activate UpdateCourseStateUI
control UpdateCourseStateController
UpdateCourseStateUI -> UpdateCourseStateController: updateCourseState(designationName, newState)
activate UpdateCourseStateController



loop newState == Open

UpdateCourseStateController -> UpdateCourseStateService: updateCourseState(String designationName, String newState)
activate UpdateCourseStateService
database CoursesRepository
 loop newState == Open
 note left of UpdateCourseStateService: Este método aplica-se também quando\n newState==Close

UpdateCourseStateService -> CoursesRepository: findCourseByDesignation(designationName)
activate CoursesRepository
CoursesRepository --> UpdateCourseStateService: designationName
 note left of UpdateCourseStateService: quando newState==Close passamos a ter\n (course.state()==Open)
UpdateCourseStateService -> Courses: updateCourseState(designationName, newState)
activate Courses
end loop

Courses --> UpdateCourseStateService: Courses

deactivate Courses
UpdateCourseStateService -> PersistenceContext: repositories()

activate PersistenceContext
PersistenceContext -> RepositoryFactory: update()
PersistenceContext -> UpdateCourseStateService: factory
deactivate PersistenceContext
UpdateCourseStateService -> RepositoryFactory: Course()
activate RepositoryFactory
RepositoryFactory -> CoursesRepository: update
deactivate RepositoryFactory
CoursesRepository -> UpdateCourseStateService: CoursesRepository
UpdateCourseStateService -> CoursesRepository: save(Course)
deactivate CoursesRepository
UpdateCourseStateService -> UpdateCourseStateController: Course
deactivate UpdateCourseStateService
UpdateCourseStateController -> UpdateCourseStateUI: Course
deactivate UpdateCourseStateController
UpdateCourseStateUI -> Manager: Confirms the operation
@enduml