@startuml
actor Teacher as Actor
participant CreateAutomaticExameUI as UI <<presentation>>
participant CreateAutomaticExameController as Controller <<aplication>>
participant Exam as Domain <<domain>>
participant RepositoryFactory as Factory <<factory>>
database ExamRepository as Repository1 <<repository>>
database QuestionRepository as Repository2 <<repository>>

Actor -> UI:Doshow()
UI -> Controller: typeQuestion()
Controller-> Domain: typesQuestions()
Domain --> Controller
Controller --> UI
UI -> UI:ShowListofQuestionTypes
UI --> Actor:Ask teacher to select type
Actor -> UI:Type selected
UI --> Actor: Ask number of Questions
Actor-> UI: Write number
UI -> Controller: CreateAutomaticExame(type, quantity)
Controller -> Domain: CreateAutomaticExame(type, quantity)
    loop option < quantity
        Domain -> Repository2: getQuestion(type)
        Repository2 --> Domain: Question
    end
Domain --> Controller: exam
Controller -> Repository1: save(exam)
Controller --> UI:exam
UI --> Actor: Show exam
@enduml