@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Student as Actor
activate Actor
participant ListExamsUI as UI <<Presentation>>
control ListStudentExamGradesController as Controller <<application>>
participant ListExamsService as Service <<application>>
participant authorizationService as AuthService <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant Factory as Factory <<factory>>
database ExamsRepository as Repository <<repository>>
database GradeOfExamRepository as gradeOfExamRepository <<repository>>
participant "theExam:Exam" as Exam <<domain>>
participant "theGradeOfExam:GradeOfExam" as GradeOfExam <<domain>>
participant elementPrinter as Printer <<presentation>>

Actor -> UI: Select the option \nto update Course state
activate UI
UI -> Controller: examOfLoggedStudent()
activate Controller
Controller -> Service: examOfLoggedStudent()
activate Service
Service -> AuthService: session.get().authenticatedUser()
activate AuthService
AuthService -> Service: loggedUser
deactivate AuthService
Service -> Persistence: findAll()
activate Persistence
Persistence -> Repository: findall()
activate Repository
Repository -> Persistence: Iterable<Exam>
deactivate Repository
Persistence -> Service: Iterable<Exam>
deactivate Persistence
    loop Iterable<GradeOfExam>
        Service -> Persistence: findAll()
        activate Persistence
        Persistence -> Factory: repositories()
        activate Factory
        Factory -> gradeOfExamRepository: findAll()
        activate gradeOfExamRepository
        gradeOfExamRepository -> Factory: Iterable<GradeOfExam>
        deactivate gradeOfExamRepository
        Factory -> Persistence: Iterable<GradeOfExam>
        deactivate Factory
        Persistence -> Service: Iterable<GradeOfExam>
        deactivate Persistence
        Service -> GradeOfExam: gradeOfExam.studentWhoDidExam().equals(loggedUser)
        activate GradeOfExam
        GradeOfExam -> GradeOfExam: grade.studentWhoDidExam().equals(loggedUser)
        GradeOfExam -> Service: GradeOfExam
        deactivate GradeOfExam
        Service -> Service: add(GradeOfExam)
    end
Service -> Controller: loggedStudentExams
deactivate Service
Controller -> UI: loggedStudentExams
deactivate Controller
UI -> Printer: elementPrinter()
activate Printer
Printer -> UI: Prints each element
deactivate Printer
UI -> Actor: Shows the Grade of each exam of the student
deactivate UI


@enduml