@startuml

class User

class UpdateSharedBoardUI {
    +doShow()
    +showInfo()
}

class UpdateSharedBoardController {
    +listOfAllUserBoards()
}

class ListBoardsService {
    +listBoardsByUser()
    +listBoardsSharedWithUser()
    +listOfAllUserBoards()
}


class ShareBoardRepository{
    +save()
    +findByUsername()
    +findBoardByTitle()
}

class ShareBoardUserRepository{
    +save()
    +findByUser()
}



User-->UpdateSharedBoardUI
UpdateSharedBoardUI-->UpdateSharedBoardController
UpdateSharedBoardController-->ListBoardsService
ListBoardsService-->ShareBoardRepository
ListBoardsService-->ShareBoardUserRepository
@enduml
