@startuml

autoactivate on

actor User as U
participant "UpdateSharedBoardUI" as UI
participant "UpdateSharedBoardController" as C
participant "ListBoardsService" as S
database "ShareBoardRepository" as SBR
database "ShareBoardUserRepository" as SBRU


U -> UI:View a board
UI -> C:listOfAllUserBoards()
C->S:listOfAllUserBoards()
S->SBR: listBoardsByUser()
SBR-->S: listOfOwnedBoards
S->SBRU:listBoardsSharedWithUser()
SBRU-->S:listOfSharedBoards
S-->C: myBoards
C-->UI: myBoards
UI->UI:Show boards
UI-->U: Select Board
U->UI: Board
UI-->U: Shows board


@enduml
