@startuml
autonumber

autoactivate on

actor Teacher
activate Teacher


Teacher -> System: Asks to add/update a question

System --> Teacher: Asks to choose course
Teacher -> System: course

System --> Teacher: Asks to choose a question type
Teacher -> System: question type
alt add question
System --> Teacher: Asks for a description
Teacher -> System: description
else update question
System --> Teacher: Asks to choose the question
Teacher -> System: question
end
System --> Teacher: Asks for file
Teacher -> System: file
System --> Teacher: Saves question

deactivate Teacher

@enduml