@startuml
actor Teacher as Actor
participant UpdateScheduleRecurringLessonUI as UI <<presentation>>
participant UpdateScheduleRecurringLessonController as Controller <<aplication>>
participant RecurringLesson as Domain <<domain>>

database RecurringLessonRepository as Repository <<repository>>

Actor -> UI: Show()
UI -> Controller:allRecurringLessons()
Controller -> ListRecurringLessonsService: allRecurringLessons()
ListRecurringLessonsService --> Controller
Controller --> UI: ListAllLessons()
UI -> UI: ShowScheduleLessons()
UI --> Actor: Ask lesson to update
Actor -> UI: Select Lesson
UI --> Actor: Show schedule and \nAsk new schedule
Actor -> UI:new Schedule
UI-> Controller: UpdateScheduleLesson\n(Lesson,Schedule)
Controller -> Domain: UpdateSchedule(Schedule)
Controller -> Repository: save(Lesson)
Controller --> UI: RecurringLessonLesson
UI --> Actor:



@enduml