@startuml

class RequestEnrollmentCoursesStudentUI {
    +elements()
    +elementPrinter()
    +elementName()
    +listHeader()
    +emptyMessage()
    +headline()
    +execute()
}

class ListCoursesStudentController {
    +allCoursesEnrollment()
}

class CourseEnrollmentRequestController {
    +courseEnrollment(selCourse)
}

class ListCoursesService {
    +getEnrollmentCourses()
}

class StudentUserRepository {
    +findByUsername()
}

class AuthorizationService {
    +session()
}

class PersistenceContext {
    -CourseEnrollmentRequestRepository: CourseEnrollmentRequestRepository
    -CourseRepository: courses
    +repositories()
}

class RepositoryFactory {
    +create()
}

class CourseEnrollmentRequestService {
    +listEnrollingCourses()
    +validateCourseEnrollmentRequest(student, course)
}

class CourseEnrollmentRequestRepository {
}

class CourseRepository {
    +findAll()
}

class SystemUser {
    +authenticatedUser()
    +username()
}

RequestEnrollmentCoursesStudentUI --> CourseEnrollmentRequestController
RequestEnrollmentCoursesStudentUI --> ListCoursesStudentController
ListCoursesStudentController --> ListCoursesService
ListCoursesService --> PersistenceContext
ListCoursesStudentController --> PersistenceContext
CourseEnrollmentRequestController --> AuthorizationService
CourseEnrollmentRequestController --> PersistenceContext
AuthorizationService --> SystemUser
SystemUser --> StudentUserRepository
PersistenceContext --> RepositoryFactory
RepositoryFactory --> CourseEnrollmentRequestRepository
RepositoryFactory --> CourseRepository
RepositoryFactory --> StudentUserRepository
CourseEnrollmentRequestController --> CourseEnrollmentRequestService
CourseEnrollmentRequestService --> PersistenceContext




@enduml