@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Student as Actor
activate Actor
participant RequestEnrollmentUI as UI <<Presentation>>
control RequestEnrollmentController as Controller <<Application>>
database CoursesRepository as CoursesRepository <<Repository>>
database StudentRepository as StudentRepository <<Repository>>
participant "theStudent:Student" as Student <<Domain>>

Actor -> UI: Select the option to \nrequest the enrollment in courses
activate UI
UI -> Controller: listAllCourses()
activate Controller
Controller -> CoursesRepository: listAllCourses()
UI -> UI: Output The Possible courses to \n request Enrollment
Actor <- UI: Ask user to select a course
Actor -> UI: Selects the course
UI -> Controller: studentRequestEnrollment(student, course)
Controller -> Student: studentRequestEnrollment(student, course)
Controller -> StudentRepository: save(Student, course)
UI <- Controller: student
Actor <- UI: Back to menu


@enduml