@startuml

class RequestEnrollmentUI {
    +doShow()
}

class RequestEnrollmentController {
    +CreateCourseEnrollmentRequest()
}

class RequestEnrollmentRepository {
}

class PersistenceContext {
    -CourseEnrollmentRequestRepository: CourseEnrollmentRequestRepository
    +repositories()
}

class RepositoryFactory {
    +create()
}

class CourseEnrollmentService {
    listEnrollingCourses()
}

class CourseEnrollmentRequest {
}

class CourseEnrollmentRequestRepository {
}

RequestEnrollmentUI --> RequestEnrollmentController
RequestEnrollmentController --> RequestEnrollmentRepository
RequestEnrollmentController --> PersistenceContext
RequestEnrollmentController --> CourseEnrollmentService
CourseEnrollmentService --> PersistenceContext
PersistenceContext --> RepositoryFactory
RepositoryFactory --> CourseEnrollmentRequestRepository
RequestEnrollmentController --> CourseEnrollmentRequest

@enduml