@startuml

class RecurringLessonUI {
    +doShow()
}

class CreateRecurringLessonController {
    +createRecurringLesson()
}

class RecurringLesson {
    +updateScheduleOfLesson(Calendar startDate, Calendar endDate, int duration)
}

class ScheduleLessonService {
    +allRecurringLessons()
    +generateRecurringLessons(Calendar startDate, Calendar endDate, int frequency)
    +validateRecurringLesson(Teacher teacher, RecurringLesson recurringLesson)
}

class RepositoryFactory {
    +create()
}

class PersistenceContext {
    -RecurringLessonRepository: RecurringLessonRepository
    +repositories()
}

class RecurringLessonRepository {
}

RecurringLessonUI --> CreateRecurringLessonController
CreateRecurringLessonController --> ScheduleLessonService
ScheduleLessonService --> PersistenceContext
CreateRecurringLessonController --> PersistenceContext
PersistenceContext --> RepositoryFactory
RepositoryFactory --> RecurringLessonRepository
CreateRecurringLessonController --> RecurringLesson

@enduml