@startuml
actor Users

autoactivate on

participant "Parent Process" as Parent
participant "Child Process" as Child
participant "SharedBoard" as Board
participant "Semaphore" as Semaphore

Users -> Parent: Ask to access SharedBoard
Parent -> Board: Create shared board
Parent -> Semaphore: Create semaphores
activate Child
Parent -> Child: Creates child processes

loop Each Child Process
    Child -> Semaphore: Wait for semaphore
    Child --> Board: Write to post-it
    Child -> Semaphore: Release semaphore
end
deactivate Child

Parent -> Child: Wait for child processes to finish
Parent -> Board: Print post-it contents

@enduml
